# Generated by Django 5.2.1 on 2025-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='correct_answers_count',
            field=models.IntegerField(default=0, help_text='Number of correct answers (grades 7-10)'),
        ),
    ]
