# Generated by Django 5.2.3 on 2025-06-30 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_userprogress_correct_answers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='consecutive_low_grades',
            field=models.IntegerField(default=0, help_text='Number of consecutive grades 0-3'),
        ),
        migrations.AlterField(
            model_name='userquestionattempt',
            name='grade',
            field=models.IntegerField(help_text='Grade received (0-10, where 0 is for empty/comments-only code)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
