# Generated by Django 5.2.1 on 2025-07-04 11:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_userprogress_consecutive_low_grades_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='manual_level',
            field=models.IntegerField(default=3, help_text="User's manually set difficulty level preference (1-5)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['manual_level'], name='practice_us_manual__eecb2e_idx'),
        ),
    ]
