# Generated by Django 5.2.1 on 2025-07-04 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions_difficulty_eval', '0003_alter_pythonprogrammingquestion_input'),
        ('practice', '0004_userprogress_manual_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_question',
            field=models.ForeignKey(blank=True, help_text='The question currently assigned to the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='instructions_difficulty_eval.pythonprogrammingquestion'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='question_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the current question was assigned', null=True),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['current_question'], name='practice_us_current_8cf717_idx'),
        ),
    ]
